version: 0.2

env:
  shell: bash
  variables:
    Code: "php"
    Success: "NowYouSeeMe"
       
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.x
      java: corretto8
    commands:
      - echo installing...
      - echo Still-Installing...
    finally:
      - echo almostInstalled...
      - echo doneInstalling!
  pre_build:
    on-failure: ABORT
    commands:
      - echo prebuilding...
      - echo stillPrebuilding...
    finally:
      - echo almostPrebuilt...
      - echo donePrebuilding!
      - wget https://github.com/grafana/k6/releases/download/v0.35.0/k6-v0.35.0-linux-amd64.rpm 
      - yum install -y k6-v0.35.0-linux-amd64.rpm 
      - yum install -y amazon-cloudwatch-agent 
      - mv statsd.json /opt/aws/amazon-cloudwatch-agent/etc/
      - ls -al /opt/aws/amazon-cloudwatch-agent/bin
      - K6_STATSD_ENABLE_TAGS=true k6 run --out statsd script.js 
      - /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent -config /opt/aws/amazon-cloudwatch-agent/etc/common-config.toml -envconfig /opt/aws/amazon-cloudwatch-agent/etc/statsd.json -pidfile /opt/aws/amazon-cloudwatch-agent/var/amazon-cloudwatch-agent.pid & 
      - sleep 10 
  build:
    on-failure: ABORT
    commands:
      - echo building...
      - echo stillBuilding...
    finally:
      - echo almostBuilt...
      - echo doneBuilding!
  post_build:
    on-failure: ABORT
    commands:
      - echo postbuilding...
      - echo stillPostbuilding...
    finally:
      - echo almostPostbuilt...
      - echo donePostbuilding!
