version: 0.2

env:
  shell: bash
  variables:
    Code: "php"
    Success: "NowYouSeeMe"
       
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.x
      java: corretto8
    commands:
      - echo installing...
      - echo Still-Installing...
    finally:
      - echo almostInstalled...
      - echo doneInstalling!
  pre_build:
    on-failure: ABORT
    commands:
      - echo prebuilding...
      - echo stillPrebuilding...
    finally:
      - echo almostPrebuilt...
      - echo donePrebuilding!
      - wget https://github.com/grafana/k6/releases/download/v0.35.0/k6-v0.35.0-linux-amd64.rpm 
      - yum install -y k6-v0.35.0-linux-amd64.rpm 
      - yum install -y amazon-cloudwatch-agent 
      - mv statsd.json /opt/aws/amazon-cloudwatch-agent/etc/
      - w 
      - uname -a
      - whoami 
      - lscpu 
      - ls -al /opt/aws/amazon-cloudwatch-agent/bin
      - K6_STATSD_ENABLE_TAGS=true k6 run --out statsd script.js 
      - /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent -config /opt/aws/amazon-cloudwatch-agent/etc/common-config.toml -envconfig /opt/aws/amazon-cloudwatch-agent/etc/statsd.json -pidfile /opt/aws/amazon-cloudwatch-agent/var/amazon-cloudwatch-agent.pid & 
      - sleep 300 
      - #yum -y install https://dl.k6.io/rpm/repo.rpm 
      - #yum -y install k6 
      - #yum -y install tree 
      - #tree / > tr.txt 
      - lscpu 
      - #yum install -y amazon-cloudwatch-agent 
      - #amazon-cloudwatch-agent-ctl -a status
      - ls -al /opt/aws/amazon-cloudwatch-agent/bin 
      - /opt/aws/amazon-cloudwatch-agent/bin/start-amazon-cloudwatch-agent 
      - #git config --global user.email "CB@aws.cs"
      - #git config --global user.name "CodeBuild" 
      - #git config --get remote.origin.url
      - #git remote show origin
      - #echo test > nf.txt 
      - #git checkout far3 
      - #/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a status 
      - #git add nf.txt
      - #git commit -m "BuildFrom" 
      - #git push -u origin far3 
  build:
    on-failure: ABORT
    commands:
      - echo building...
      - echo stillBuilding...
    finally:
      - echo almostBuilt...
      - echo doneBuilding!
  post_build:
    on-failure: ABORT
    commands:
      - echo postbuilding...
      - echo stillPostbuilding...
    finally:
      - echo almostPostbuilt...
      - echo donePostbuilding!
artifacts:
  files:
    - tr.txt 
  s3-prefix: GHST
