version: 0.2

env:
  shell: bash
  variables:
    Code: "php"
    Success: "NowYouSeeMe"
       
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.x
      java: corretto8
    commands:
      - echo installing...
      - echo Still-Installing...
    finally:
      - echo almostInstalled...
      - echo doneInstalling!
  pre_build:
    on-failure: ABORT
    commands:
      - echo prebuilding...
      - echo stillPrebuilding...
    finally:
      - echo almostPrebuilt...
      - echo donePrebuilding!
      - w 
      - uname -a
      - whoami 
      - lscpu 
      - #yum -y install https://dl.k6.io/rpm/repo.rpm 
      - #yum -y install k6 
      - #yum -y install tree 
      - #tree / > tr.txt 
      - lscpu 
      - yum install amazon-cloudwatch-agent 
      - amazon-cloudwatch-agent-ctl -a status
      - #git config --global user.email "CB@aws.cs"
      - #git config --global user.name "CodeBuild" 
      - #git config --get remote.origin.url
      - #git remote show origin
      - #echo test > nf.txt 
      - #git checkout far3 
      - #/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a status 
      - #git add nf.txt
      - #git commit -m "BuildFrom" 
      - #git push -u origin far3 
  build:
    on-failure: ABORT
    commands:
      - echo building...
      - echo stillBuilding...
    finally:
      - echo almostBuilt...
      - echo doneBuilding!
  post_build:
    on-failure: ABORT
    commands:
      - echo postbuilding...
      - echo stillPostbuilding...
    finally:
      - echo almostPostbuilt...
      - echo donePostbuilding!
artifacts:
  files:
    - tr.txt 
  s3-prefix: GHST
