version: 0.2

env:
  shell: bash
  variables:
    Code: "php"
    Success: "NowYouSeeMe"
       
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.x
      java: corretto8
    commands:
      - echo installing...
      - echo Still-Installing...
    finally:
      - echo almostInstalled...
      - echo doneInstalling!
  pre_build:
    on-failure: ABORT
    commands:
      - echo prebuilding...
      - echo stillPrebuilding...
    finally:
      - echo almostPrebuilt...
      - echo donePrebuilding!
      - ls -al
      - zip -r public * .ebextensions/* 
      - ls -al
      - aws s3 ls 
      - git status 
      - git stash 
      - git checkout far3
      - git stach pop
      - git status 
      - #npm version 
      - #cdk version 
      - #aws s3 cp --recursive . s3://elelelele/php/
      - #exit 0
      - #ls fileNotFound!
  build:
    on-failure: ABORT
    commands:
      - echo building...
      - echo stillBuilding...
    finally:
      - echo almostBuilt...
      - echo doneBuilding!
  post_build:
    on-failure: ABORT
    commands:
      - echo postbuilding...
      - echo stillPostbuilding...
    finally:
      - echo almostPostbuilt...
      - echo donePostbuilding!
artifacts:
  files:
    - index.php
    - styles.css
  s3-prefix: GHST
