version: 0.2

env:
  shell: bash
  variables:
    Code: "php"
    Success: "NowYouSeeMe"
       
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.x
      java: corretto8
    commands:
      - echo installing...
      - echo Still-Installing...
    finally:
      - echo almostInstalled...
      - echo doneInstalling!
  pre_build:
    on-failure: ABORT
    commands:
      - echo prebuilding...
      - echo stillPrebuilding...
    finally:
      - echo almostPrebuilt...
      - echo donePrebuilding!
      - ls -al
      - zip -r public * .ebextensions/* 
      - ls -al
      - aws s3 ls 
      - sleep 60 
      - git config --global user.email "CB@aws.cs"
      - git config --global user.name "CodeBuild" 
      - git status 
      - #git stash 
      - git checkout far3
      - #git stash pop
      - git status 
      - git add public.zip
      - git commit -m "Commit from inside CB!" 
      - #git push -u origin far3
      -	git config --get remote.origin.url 
      - git remote show origin
      - sleep 300 
      - #npm version 
      - #cdk version 
      - #aws s3 cp --recursive . s3://elelelele/php/
      - #exit 0
      - #ls fileNotFound!
  build:
    on-failure: ABORT
    commands:
      - echo building...
      - echo stillBuilding...
    finally:
      - echo almostBuilt...
      - echo doneBuilding!
  post_build:
    on-failure: ABORT
    commands:
      - echo postbuilding...
      - echo stillPostbuilding...
    finally:
      - echo almostPostbuilt...
      - echo donePostbuilding!
artifacts:
  files:
    - index.php
    - styles.css
  s3-prefix: GHST
